version: "3.9"
services:
  mediafilesbox-webapi:
    build:
      context: .
      dockerfile: MediaFilesBox.WebApi/Dockerfile
    ports:
      - "5080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - "sqlserver-db"
  sqlserver-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"